name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: poetry install --all-extras
      - name: Run ruff linter
        run: poetry run ruff check --output-format github
      - name: Run ruff formatter
        run: poetry run ruff format --check .
      - name: Run mypy type checker
        run: poetry run mypy .

  test:
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
      - name: Install dependencies
        run: poetry install --all-extras
      - name: Run unit tests
        run: poetry run pytest tests/unit/